---
locale:
  enabled:
    - en_US.UTF-8
  default: en_US.UTF-8
  language: en_US.UTF-8
  # optional. if not set, things will default to locale.default
  monetary: en_US.UTF-8
  # optional. if not set, things will default to locale.default
  time: en_US.UTF-8
