---
cli_required:
  - cli_default_shell is defined
  - cli_terminal_packages is defined and cli_terminal_packages|length > 0

cli_default_shell: zsh
cli_shell_packages:
  - bash
  - zsh

cli_terminal_packages:
  - rxvt-unicode
  - xterm

cli_aur_packages:
  - urxvt-font-size-git # on-the-fly URxvt font size adjustments
