# This playbook should only be executed once per installation: right after
# finishing the initial archlinux installation.
- hosts: localhost
  connection: local
  roles:
    - role: pacman
      tags: ['pacman', 'aur']
    - role: locale
      tags: ['locale', 'timezone', 'ntp']
    #- power
