# This playbook should only be executed once per installation: right after
# finishing the initial archlinux installation.
- hosts: localhost
  connection: local
  roles:
    - pacman
      #- localization
    #- power
