- hosts: localhost
  connection: local
  vars_files:
    - defaults.yml
  roles:
    - role: pacman
      tags: ['pacman', 'aur']
    - role: sudo
      tags: ['sudo']
    - role: locale
      tags: ['locale', 'timezone', 'ntp']
    - role: network
      tags: ['network']

    - role: xorg
      tags: ['xorg']

  # power / suspend / laptop power
  # nvidia
