- hosts: localhost
  connection: local
  vars_files:
    - defaults.yml
  pre_tasks:
    - name: check required
      assert:
        that:
          - aur_helper is defined
          - aur_user is defined
  roles:
    - role: user
      tags: ['user']
    - role: gui
      tags: ['gui']
    - role: cli
      tags: ['cli']
    - role: git
      tags: ['git']

  # dotfiles
  # UI config
