- hosts: localhost
  connection: local
  tags: ['graphics', 'nvidia']
  pre_tasks:
    - name: check required
      assert:
        that:
          - aur_helper is defined
          - aur_user is defined
    - name: found out Nvidia model
      shell:
        cmd: lshw -class display -xml | xq -r .list.node.product
      register: lshw_nvidia
    - name: there should be only one nvidia
      assert:
        that:
          - lshw_nvidia.stdout_lines|length == 1
    - name: set nvidia model as fact
      set_fact:
        nvidia_model: "{{ lshw_nvidia.stdout_lines[0] }}"

  roles:
    - role: video
      tags: ['video']
    - role: nvidia
      tags: ['nvidia', 'latest']
      when: "'GeForce GTX 1660' in nvidia_model"

