= Ansible and ArchLinux

Collection of ansible playbooks and roles used to install and maintain my personal archlinux installation.

The way it works is that for each new machine you want to install and configure, you create a ansible configuration under `host_vars/<hostname>` so you can run a set of playbooks such as:

* install system tools such as hardware drivers, login managers, power config, etc
* setup and configure a new user such as personal, work, etc

== Requirements

Before using this you need to ensure you have already have a barebones archlinux up and running with the following pacman packages:
* `ansible`
* `python`
* `python-passlib`

We also require a specific ansible module to install packages from the AUR which is configured to be added to ansible's `$ANSIBLE_LIBRARY` in `ansible.cfg`

== Initial installation

=== Configuration files

=== Run playbook

[source,shell]
----
ansible-playbook 01-system.yml
----

== Testing

You can use docker to test a local installation.

Pull the latest archlinux image and then execute it as:
[source,shell]
----
$ docker run -d --name archlinux -v $(pwd):/ansible archlinux journalctl -f
----

You can then `exec` into it follow this document.

== Playbooks

* system configuration
* user configuration
*

Convert my ArchLinux [installation steps][install-steps] to an ansible role, much like [dharmab/ansible-archlinux][dharmab-ansible].
Use GNU stow to manage my [dotfiles][ntfc-dotfiles].




== References

Verify role variables are set: https://thoughts.t37.net/documenting-your-ansible-roles-interface-and-making-other-peoples-life-easier-604e5172837b?gi=fc6917f3204b

Check for required variables in role: https://coderleaf.wordpress.com/2017/07/06/ansible-check-for-required-variables-before-role-execution/

[dharmab-ansible]: https://github.com/dharmab/ansible-archlinux
[ntfc-dotfiles]: https://github.com/ntfc/dotfiles
[install-steps]: https://gist.github.com/ntfc/5dd78a7dc6746c95f786
