= Ansible and ArchLinux
Nuno Carvalho <me@ntfc.me>
:toc:
:dotfiles: https://gitlab.com/ntfc/dotfiles.git[dotfiles]
:json_querying: https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#json-query-filter[JSON Querying]
:variables_and_vaults: https://docs.ansible.com/ansible/latest/user_guide/playbooks_best_practices.html#variables-and-vaults[Variables and Vaults]

// disable preamble
[.normal]
Collection of Ansible playbooks to install and maintain personal ArchLinux
installations.

The way it works is that for each new machine you want to install and
configure, you create an ansible configuration under `host_vars/<hostname>/` so
you can run a set of playbooks such as:

* install system tools such as hardware drivers, login managers, power config,
  etc
* setup and configure a new user such as personal, work, etc

== Getting started

=== Requirements

IMPORTANT: Most of playbooks require a stow managed {dotfiles} directory to be used!

Before using this you need to ensure you have already have a barebones archlinux up and running with the following pacman packages:

* `ansible`
* `python`
* `python-passlib`
* `python-jmespath` (for {json_querying} e.g. in the `agenda` role)
* `git` (only used to clone this repo and the submodule)

All of the above can be installed with an helper script:

[source,shell]
----
./install_requirements.sh
----

We also require a specific ansible module to install packages from the AUR which is configured to be added to ansible's `$ANSIBLE_LIBRARY` in `ansible.cfg`. For this there is no need to install anything but rather just making the git submodule is checked out as follows:

[source,shell]
----
# needed in the first run only
git submodule update --recursive --init
# used to update the submodule
git submodule update --recursive --remote
----

IMPORTANT: *TODO:* use the ansible-galaxy role dependency instead of the gitsubmodule

We also require a couple of ansible modules available in either ansible galaxy or git repositories.

These can be installed with `ansible-galaxy`:

[source,shell]
----
ansible-galaxy role install -r roles/requirements.yml
----

=== Create host specific variables

When adding a new machine it is necessary to define some common variables in YAML files under `host_vars/<hostname>/` (replace `<hostname>` with the local machine hostname).
There will be two files in this directory (as described in {variables_and_vaults}):

* `vars.yml`: a plain text YAML
  - the sensitive variables will reference a `vault_` prefixed variable stored in `vault.yml`
* `vault.yml`: a vault encrypted YAML file with sensitive variables
  - all variables should be prefixed with `vault_` that will be read by `vars.yml`

The `vault.yml` file will be encrypted with a password that can be *locally* stored in `vault-pwd`.
This file is set to be ignored in `.gitignore` and it should make interacting with playbooks easier (no need to type password in every run).

=== Configuration files

TODO: create an interactive ansible playbook that creates a basic configuration file

Before running anything, we need to define what we need to configure.
This is done by creating a new file in `host_vars/localhost/main.yml`.

== Run playbooks

With the configuration out of the way we can start running playbooks.

All playbooks are added in `playbooks/`, and in each of them you should find a small description of what they do.

Here are some useful `ansible-playbook` commands:

[source,shell]
----
# list available tasks. note the tags are shown in square brackets
ansible-playbook 01-system.yml --list-tasks
# list tags
ansible-playbook 01-system.yml --list-tags
# run a particular tag
ansible-playbook 01-system.yml --tags pacman
# run all the tasks
ansible-playbook 01-system.yml
# run one specific task, and confirm each task before running
ansible-playbook 01-system.yml --step --start-at-task="insert task name here"
----

Gotchas:

* For tmux, we need to run `tmux source-file ~/.tmux.conf` manually

== Testing

=== Vagrant + VirtualBox

We can use Vagrant with a Virtualbox provider, where this repository is mounted on the virtualbox VM to better mmimic the localhost scenario.

Start by installing VirtualBox and Vagrant on the host machine.

To correctly start virtualbox `modprobe` the following modules (taken from https://gist.github.com/ntfc/77a5160eb69c3ce4fa88):
[source,shell]
----
$ modprobe vboxdrv vboxnetadp vboxnetflt vboxpci
----

Then you can start the VM with:
[source,shell]
----
$ vagrant up
----

The `Vagrantfile` in this repository configures a password based SSH for ease of access.

[source,shell]
----
$ vagrant ssh
----

Now you should be inside the VM.

Run `/ansible/install_requirements.sh` (reboot if required) and then you can start running playbooks.

=== Docker

WARNING: You will quickly run into troubles when using docker since service management is not available.

You can use docker to test a local installation.

Pull the latest archlinux image and then execute it as:
[source,shell]
----
$ docker run -d --name archlinux -v $(pwd):/ansible archlinux journalctl -f
----

You can then `exec` into it follow this document.



== References

* https://github.com/dharmab/ansible-archlinux[dharmab/ansible-archlinux]
* https://gist.github.com/ntfc/5dd78a7dc6746c95f786[My (old) ArchLinux installation steps]
* https://thoughts.t37.net/documenting-your-ansible-roles-interface-and-making-other-peoples-life-easier-604e5172837b[Documenting your Ansible roles interface (and making other people’s life easier)]
* https://coderleaf.wordpress.com/2017/07/06/ansible-check-for-required-variables-before-role-execution/[Check for required variables before role]

