---
- name: check required
  assert:
    that:
      - "{{ item }}"
  with_items: "{{ user_required }}"

- name: create user {{ user_name }}
  user:
    name: "{{ user_name }}"
    password: "{{ user_password }}"
    group: "{{ user_group }}"
    groups: "{{ user_groups }}"
    create_home: "{{ user_create_home }}"
    state: present
  become: yes

- name: add user to sudoers
  template:
    src: user_name_sudoers.j2
    dest: "/etc/sudoers.d/{{ user_name }}"
    validate: 'visudo --check --file=%s'
  when: user_is_sudoer|default(False)

- import_tasks: dotfiles.yml
  vars:
    become_user: "{{ user_name }}"
    become: yes
  when: user_dotfiles_url is defined
