---
- block:
  - name: install utilities (browsers, file explorer, image viewer, etc)
    pacman:
      name:
        - firefox
        - chromium
        - ffmpeg
        - thunar
        - thunar-volman
        - thunar-archive-plugin
        - gvfs
        - vlc
        - mousepad
        - geany
        - geany-plugins
        - feh
        - viewnior
        - keepassxc
        - xsel
        - xbindkeys
        - volumeicon
        - light
        - clementine
        - rofi
        - zathura
        - zathura-ps
        - zathura-djvu
        - zathura-pdf-mupdf
        - qbittorrent
        - copyq
      state: present
    become: yes

  - name: install volnoti
    include: cower.yml aur_package=volnoti

  - name: stow some utilities settings
    command: "stow -d ~/dotfiles -t {{ item.target }} {{ item.package }}"
    with_items:
      - { target: ~/, package: copyq }
      - { target: ~/, package: rofi }
    become: yes
    become_user: "{{ archlinux_user_name }}"

  tags:
    - applications
