---
- block:
  - name: install pulseaudio
    pacman:
      name:
        - pulseaudio
        - pavucontrol
        - pamixer
        - paprefs
        - pulseaudio-alsa
        - pulseaudio-bluetooth
        - pulseaudio-jack
        - lib32-libpulse
      state: present
    become: yes

  - name: install audio plugins
    pacman:
      name:
        - gst-plugins-base
        - gst-plugins-good
        - gst-plugins-bad
        - gst-plugins-ugly
        - libao
        - lib32-alsa-plugins
        - xfce4-pulseaudio-plugin
      state: present
    become: yes

  - name: copy audio configurations
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dst }}"
      mode: 0644
    with_items:
      - { src: modprobe.d/oss.conf, dst: /etc/modprobe.d/oss.conf }
      - { src: modprobe.d/nobeep.conf, dst: /etc/modprobe.d/nobeep.conf }
      - { src: libao.conf, dst: /etc/libao.conf }
    become: yes

  tags:
    - audio
