---
- block:
  - name: add cower key
    shell: "gpg --keyserver pool.sks-keyservers.net --recv-keys {{ cower_key_id }}"
    become: yes
    become_user: "{{ archlinux_user_name }}"

  - name: clone cower
    git:
      accept_hostkey: yes
      repo: "{{ cower_git }}"
      dest: /tmp/cower
    become: yes
    become_user: "{{ archlinux_user_name }}"

  - name: install cower
    shell: 'cd /tmp/cower && makepkg --noconfirm -f -s -i'
    become: yes
    become_user: "{{ archlinux_user_name }}"

  - name: cleanup cower
    file: path={{ item }} state=absent
    with_items:
      - '/tmp/cower'
    become: yes
    become_user: "{{ archlinux_user_name }}"

  - name: install yay
    include: cower.yml aur_package=yay

  tags:
    - aur
