---
- block:
  - name: install bluetooth packages
    pacman:
      name:
        - bluez
        - bluez-libs
        - bluez-utils
        - blueman
      state: present
    become: yes

  tags:
    - bluetooth
