---
- name: install devel packages
  pacman: name={{ item }} state=present
  with_items:
    - base-devel
    - gdb
    - jdk8-openjdk
    - maven
    - python
    - python2
  become: yes

- name: set default jdk
  command: "/usr/bin/archlinux-java set java-8-openjdk"
  become: yes

- name: stow symlink environment config file
  command: "/usr/bin/stow -d /home/{{ archlinux_user_name }}/dotfiles -t /etc environment"
  become: yes
