---
- block:
  - name: install git and stow
    pacman:
      name:
        - git
        - stow
        - diff-so-fancy
      state: present
    become: yes

  - name: get my dotfiles from {{ dotfiles_git }}
    git:
      accept_hostkey: yes
      repo: "{{ dotfiles_git }}"
      dest: ~/dotfiles
    become: yes
    become_user: "{{ archlinux_user_name }}"

  - name: stow git settings
    command: "stow -d ~/dotfiles -t ~/ git"
    become: yes
    become_user: "{{ archlinux_user_name }}"

  - name: configure "{{ archlinux_user_name }}" email as "{{ archlinux_user_email }}"
    template:
      src: gitconfig-private.j2
      dest: ~/.gitconfig-private
    become: yes
    become_user: "{{ archlinux_user_name }}"

  tags:
    - git
    - stow
