---
- block:
  - name: install gui packages
    pacman:
      name:
        - lightdm
        - lightdm-gtk-greeter
        - lxappearance
        - arandr
        - numlockx
        - lxinput
        - gtk-engines
        - gnome-icon-theme
        - hicolor-icon-theme
        - adwaita-icon-theme
        - redshift

  - name: configure lightdm
    lineinfile:
      dest: /etc/lightdm/lightdm.conf
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    with_items:
      - { regexp: '^greeter-session=', line: 'greeter-session=lightdm-gtk-greeter' }
      - { regexp: '^greeter-setup-script=', line: 'greeter-setup-script=/usr/bin/numlockx on' }
    become: yes

  - name: enable lightdm service
    service: name=lightdm enabled=yes
    become: yes

  - name: stow gui user settings
    command: "stow -d ~/dotfiles -t {{ item.target }} {{ item.package }}"
    with_items:
      - { target: ~/, package: gtk3 }
      - { target: ~/, package: icons }
      - { target: ~/, package: redshift }
    become: yes
    become_user: "{{ archlinux_user_name }}"

  - name: stow "{{ archlinux_user_name }}" startup settings
    command: "stow -d ~/dotfiles -t ~/ startup"
    become: yes
    become_user: "{{ archlinux_user_name }}"

  - name: stow root startup settings
    command: "stow -d /home/{{ archlinux_user_name }}/dotfiles -t /opt xdg-autostart"
    become: yes

  - name: change lightdm session-setup-script
    lineinfile:
      dest: /etc/lightdm/lightdm.conf
      regexp: '^session-setup-script='
      line: 'session-setup-script=/opt/remove-xdg-autostart'
    become: yes

  - name: install mons
    include: cower.yml aur_package=mons

  - name: install compton
    pacman: name=compton state=present
    become: yes

  - name: stow compton settings
    command: "stow -d ~/dotfiles -t ~/ compton"
    become: yes
    become_user: "{{ archlinux_user_name }}"

  - name: install xcursor-human
    include: cower.yml aur_package=xcursor-human

  - name: install gnome-colors-icon-theme
    include: cower.yml aur_package=gnome-colors-icon-theme
    tags:
      - slow
      - gnome-colors-icon-theme

  - name: install zuki-themes
    include: cower.yml aur_package=zuki-themes
    tags:
      - slow
      - zuki-themes

  - name: install vertex-themes-git
    include: cower.yml aur_package=vertex-themes-git
    tags:
      - slow
      - vertex-themes
    
  tags:
    - gui
