---
- block:
  - name: set timezone to {{ default_timezone }}
    file:
      src: /usr/share/zoneinfo/{{ default_timezone }}
      dest: /etc/localtime
      state: link
    become: yes

  - name: write all availables locales to /etc/locale.gen
    command: "locale-gen"
    become: yes

  - name: enable the necessary locales
    lineinfile: 
      dest: /etc/locale.gen
      regexp: "^{{ item }}"
      insertafter: "^#{{ item }}"
      line: "{{ item }}"
      state: present
    with_items:
      - 'en_US.UTF-8 UTF-8'
      - 'en_GB.UTF-8 UTF-8'
      - 'pt_PT.UTF-8 UTF-8'
      - 'de_DE.UTF-8 UTF-8'
    become: yes

  - name: add locale configuration to /etc/locale.conf
    lineinfile:
      dest: /etc/locale.conf
      create: yes
      state: present
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    with_items:
      - { regexp: '^LANG=', line: 'LANG=en_US.UTF-8' }
      - { regexp: '^LANGUAGE=', line: 'LANGUAGE=en_US.UTF-8' }
      - { regexp: '^LC_MONETARY=', line: 'LC_MONETARY=pt_PT.UTF-8' }
      - { regexp: '^LC_TIME=', line: 'LC_TIME=en_GB.UTF-8' }
    become: yes
  tags:
    - locale
