---
#- include: connman.yml
#- include: pacman.yml
#- include: user.yml
#- include: git.yml
#- include: stow.yml
#- include: devel.yml
#- include: vim.yml
#- include: sudo.yml
#- include: aur.yml
#- include: sysutils.yml
#- include: xorg.yml
#- include: tty.ymlA
# TODO: merge openbox and gui, or simplify openbox
#- include: openbox.yml
#- include: gui.yml

