---
# TODO: re-organize this with imports as soon as #13861 and #13962 are resolved
- name: install connman
  pacman: name={{ item }} state=present
  become: yes
  with_items:
    - connman
      #- wpa_supplicant

- name: enable connman
  service: name=connman state=started enabled=yes
  become: yes

- name: create connman configuration dir
  file: path=/etc/connman state=directory 
  become: yes
  
- name: copy connman configuration
  copy:
    src: connman/main.conf
    dest: /etc/connman/main.conf
    mode: 0644
  become: yes

- name: install reflector
  pacman: name=reflector state=present
  become: yes

- name: enable pacman multilib repo
  ini_file: 
      backup: yes
      dest: /etc/pacman.conf
      section: multilib
      option: Include
      value: /etc/pacman.d/mirrorlist
  become: yes

- name: check if mirrorlist was recently updated
  # find is not working for some reason
  #find: paths="/etc/pacman.d/mirrorlist" age=7d file_type="file"
  stat: path="/etc/pacman.d/mirrorlist"
  register: mirrorlist_age

- name: update pacman mirrorlist with reflector
  command: reflector --country "Portugal" -l 200 -p http --sort rate --save /etc/pacman.d/mirrorlist
  become: yes
  # find is not working for some reason
  #when: "{{ mirrorlist_age.matched }} > 0"
  when: "{{ mirrorlist_age.stat.mtime }} < {{ ansible_date_time.epoch|int - (60 * 60 * 24 * 7) }}"

- name: update pacman package lists
  command: pacman -Syy --noconfirm
  become: yes

- name: perform full upgrade
  pacman: upgrade=yes
  become: yes

- name: create user "{{ archlinux_user_name }}"
  user: 
    name: "{{ archlinux_user_name }}"
    password: "{{ archlinux_user_password }}"
    createhome: yes
    group: users
    groups: wheel
    state: present
  become: yes

- name: install git
  pacman: name=git state=present
  become: yes

- name: configure user name as "{{ archlinux_user_name }}"
  command: "/usr/bin/git config --global user.name \"{{ archlinux_user_name }}\""
  become: yes
  become_user: "{{ archlinux_user_name }}"

- name: configure "{{ archlinux_user_name }}" email as "{{ archlinux_user_email }}"
  command: "/usr/bin/git config --global user.email \"{{ archlinux_user_email }}\""
  become: yes
  become_user: "{{ archlinux_user_name }}"

- name: install stow
  pacman: name=stow state=present
  become: yes

- name: get my dotfiles
  git:
    accept_hostkey: yes
    repo: "{{ dotfiles_git }}"
    dest: ~/dotfiles
  become: yes
  become_user: "{{ archlinux_user_name }}"

- name: install devel packages
  pacman: name={{ item }} state=present
  with_items:
    - base-devel
    - gdb
    - jdk7-openjdk
    - jdk8-openjdk
    - maven
    - python
    - python2
  become: yes

- name: set default jdk
  command: "/usr/bin/archlinux-java set java-8-openjdk"
  become: yes

- name: stow symlink environment config file
  command: "/usr/bin/stow -d /home/{{ archlinux_user_name }}/dotfiles -t /etc environment"
  become: yes
