---
- name: install reflector
  pacman: name=reflector state=present
  become: yes

- name: enable pacman multilib repo
  ini_file: 
      backup: yes
      dest: /etc/pacman.conf
      section: multilib
      option: Include
      value: /etc/pacman.d/mirrorlist
  become: yes

- name: update pacman mirrorlist with reflector
  command: reflector --country "Portugal" -l 200 -p http --sort rate --save /etc/pacman.d/mirrorlist
  become: yes

- name: update pacman package lists
  command: pacman -Syy --noconfirm
  become: yes

- name: perform full upgrade
  pacman: upgrade=yes
  become: yes


