---
- name: make sure the vim package is not installed
  pacman: name=vim state=absent
  become: yes

- name: install gvim
  pacman: name=gvim state=present
  become: yes

- name: stow symlink vim configs
  command: "/usr/bin/stow -d ~/dotfiles -t ~/ vim"
  become: yes
  become_user: "{{ archlinux_user_name }}"

- name: install Vundle
  git:
    accept_hostkey: yes
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: "~/.vim/bundle/Vundle.vim"
  become: yes
  become_user: "{{ archlinux_user_name }}"

- name: run Vundle plugin update
  command: "/usr/bin/vim +PluginUpdate +qall!"
  become: yes
  become_user: "{{ archlinux_user_name }}"
