---
- name: install xorg (with nvidia)
  pacman: name={{ item }} state=present
  with_items:
    - xorg
    - xorg-server-utils
    - nvidia-340xx
  become: yes

- name: install touchpad/keyboard libs
  pacman: name={{ item }} state=present
  with_items:
    - xorg-xinput
    - xf86-input-libinput
  become: yes

- name: stow X11 configs
  command: "stow -d /home/{{ archlinux_user_name }}/dotfiles -t / X11"
  become: yes

