---
# Default values used for pacman configuration

# OPTIONAL: Prefered country to which use Archlinux mirrors. Will install `reflector` if defined
pacman_mirror_country: Germany

# list of pacman packages used for common operations (and that don't require any extra configuration)
pacman_base_packages:
  - base-devel # compile stuff
  - curl # download stuff
  - sudo

# the AUR helper
aur_helper: yay
# user to be used for ansible AUR installations
aur_user: aur
