---
# Default values used for pacman configuration

# list of pacman packages nice to have installed and don't require installation
pacman_base_packages:
  - base-devel # compile stuff

# the AUR helper
aur_helper: yay
# user to be used for ansible AUR installations
aur_user: aur
