---
# vars file for archlinux
default_country: Germany

#dotfiles_git: git@github.com:ntfc/dotfiles.git
dotfiles_git: https://github.com/ntfc/dotfiles

cower_git: https://aur.archlinux.org/cower.git

infinality_key_id: 962DDE58

cower_key_id: 1EB2638FF56C0C53
