---
- name: check required
  assert:
    that:
      - "{{ item }}"
  with_items: "{{ xorg_required }}"

- name: install xorg packages
  pacman:
    name: "{{ xorg_packages }}"
    state: present
  become: yes

# TODO: install touchpad drivers only if relevant
# TODO: stow xorg stuff only relevant for current machine
#
- name: stow startup settings, including xorg
  command: "stow -d {{ user_dotfiles_path }} -t ~ startup"
  become: yes
  become_user: "{{ user_name }}"
