---
- name: install bluetooth
  pacman:
    name:
      - bluez
      - bluez-libs
      - bluez-utils
      - blueman
    state: present
  become: yes

- name: install pulseaudio modules
  aur:
    name:
      - pulseaudio-modules-bt
      - libldac
    use: "{{ aur_helper }}"
  become: yes
  become_user: "{{ aur_user }}"

- name: start and enable bluetooth service
  service:
    name: bluetooth
    enabled: yes
    state: started
  become: yes
  when: bluetooth_enabled|default(False)
