---
- name: check required
  assert:
    that:
      - "{{ item }}"
  with_items: "{{ gui_required }}"

- name: install common gui tools and themes
  pacman:
    name: "{{ gui_common_packages }}"
    state: present
  become: present
  tags: ['gui-common']

- include: xorg.yml
  tags: ['xorg']

- include: fonts.yml
  tags: ['fonts']

- include: openbox.yml
  when: gui_wm_default == 'openbox'
  tags: ['wm', 'openbox']

- name: install rofi
  pacman:
    name: rofi
    state: present
  become: yes

- name: stow rofi
  command: "stow -d {{ user_dotfiles_path }} -t ~ rofi"
  become: yes
  become_user: "{{ user_name }}"

- name: stow startup settings with Xorg and WM
  command: "stow -d {{ user_dotfiles_path }} -t ~ startup"
  become: yes
  become_user: "{{ user_name }}"
