---
- name: install openbox packages
  pacman:
    name: "{{ gui_openbox_packages }}"
    state: present
  become: yes

- name: install openbox AURs
  aur:
    use: "{{ aur_helper }}"
    name: "{{ gui_openbox_aur }}"
  become: yes
  become_user: "{{ aur_user }}"

- name: stow openbox config
  command: "stow -d {{ user_dotfiles_path }} -t ~ openbox"
  become: yes
  become_user: "{{ user_name }}"

- name: stat /opt/setlayout
  stat:
    path: /opt/setlayout
  register: setlayout

- name: copy setlayout.c
  copy:
    src: setlayout.c
    dest: /tmp/setlayout.c
  when: not setlayout.stat.exists

- name: compile setlayout.c
  command: "gcc -o /opt/setlayout /tmp/setlayout.c -lX11"
  become: yes
  when: not setlayout.stat.exists

- name: check if nm-applet xdg autostart exists
  stat:
    path: /etc/xdg/autostart/nm-applet.desktop
  register: nm_applet_desktop

- name: copy nm-applet xdg autostart to user config
  shell: "mkdir -p /home/{{ user_name }}/.config/autostart && cp /etc/xdg/autostart/nm-applet.desktop /home/{{ user_name }}/.config/autostart/"
  become: yes
  become_user: "{{ user_name }}"
  when: nm_applet_desktop.stat.exists

- name: hide the nm-applet autostart for the user
  ini_file:
    path: "/home/{{ user_name }}/.config/autostart/nm-applet.desktop"
    section: "Desktop Entry"
    option: "Hidden"
    value: "true"
    state: present
  become: yes
  become_user: "{{ user_name }}"
  when: nm_applet_desktop.stat.exists
