---
- name: install openbox packages
  pacman:
    name: "{{ gui_openbox_packages }}"
    state: present
  become: yes

- name: install openbox AURs
  aur:
    use: "{{ aur_helper }}"
    name: "{{ gui_openbox_aur }}"
  become: yes
  become_user: "{{ aur_user }}"

- name: stow openbox config
  command: "stow -d {{ user_dotfiles_path }} -t ~ openbox"
  become: yes
  become_user: "{{ user_name }}"

- name: stat /opt/setlayout
  stat:
    path: /opt/setlayout
  register: setlayout

- name: copy setlayout.c
  copy:
    src: setlayout.c
    dest: /tmp/setlayout.c
  when: not setlayout.stat.exists

- name: compile setlayout.c
  command: "gcc -o /opt/setlayout /tmp/setlayout.c -lX11"
  become: yes
  when: not setlayout.stat.exists

