locale:
  enabled:
    - en_US.UTF-8
    - en_GB.UTF-8
    - pt_PT.UTF-8
    - de_DE.UTF-8
  language: en_US.UTF-8
  monetary: pt_PT.UTF-8
  time: en_GB.UTF-8

timezone: Europe/Berlin

pacman.mirror.country: Germany

aur.helper: yay

packages:
  base:
    - base-devel
    - cronie
    - curl
    - htop
    - net-tools
    - nmap
    - rsync
    - wget
  
user:
  name: ntfc
  passsword: ""
  email: me@ntfc.me

