- name: install intel drivers
  pacman:
    name:
      - mesa
      - lib32-mesa
    state: present
  become: yes

- name: ensure xf86-video-intel is not installed
  pacman:
    name: xf86-video-intel
    state: absent
  become: yes

# TODO: disable VSYNC https://wiki.archlinux.org/index.php/Intel_graphics#Disable_Vertical_Synchronization_(VSYNC)
