---
- name: check required
  assert:
    that:
      - "{{ item }}"
  with_items: "{{ network_required }}"

- name: install base network tools
  pacman:
    name: "{{ network_base_packages }}"
    state: present
  become: yes
  when: network_base_packages is defined

- name: install aur network packages
  aur:
    name: "{{ network_aur_packages }}"
    use: "{{ aur_helper }}"
  become: yes
  become_user: "{{ aur_user }}"
  when: network_aur_packages is defined

- include: connman.yml
  when: network_connman_install
  tags: ['connman']

- include: netctl.yml
  when: network_netctl_install
  tags: ['netctl']

- include: networkmanager.yml
  when: network_networkmanager_install
  tags: ['networkmanager']

