---
- name: install networkmanager
  pacman:
    name:
      - networkmanager
      - network-manager-applet
      - nm-connection-editor
      - networkmanager-openvpn
    state: present
  become: yes

# don't start the service to not break currently open connection
- name: enable NetworkManager service
  service:
    name: NetworkManager
    enabled: yes
  when: network_default_manager == 'networkmanager'
  become: yes

- name: disable NetworkManager service
  service:
    name: NetworkManager
    enabled: no
  when: network_default_manager != 'networkmanager'
  become: yes
