---
- include: install_pipewire.yml
  when: audio_use_pipewire|default(False)
  tags: ['pipewire']

- include: install_pulseaudio.yml
  when: not audio_use_pipewire|default(False)
  tags: ['pulseaudio']

- name: blacklist oss
  copy:
    src: blacklist_oss.conf
    dest: /etc/modprobe.d/blacklist_oss.conf
    mode: 0644
  become: yes

- name: set the default sound cards order
  template:
    src: default-sound-card.conf.j2
    dest: /etc/modprobe.d/alsa-base.conf
    mode: 0644
  become: yes
  when: audio_alsa_conf|default(False)

  # I am not sure this is needed
- name: configure libao
  copy:
    src: libao.conf
    dest: /etc/libao.conf
    mode: 0644
  become: yes

- include: sof.yml
  tags: ['sof']

# consider doiung this https://www.reddit.com/r/wine_gaming/comments/7qm8wp/for_anyone_with_sound_issues_on_grand_theft_auto/
# for issues with games?
# seems to work with dirt
