# To prevent applications from using ALSA's OSS emulation and bypassing PulseAudio (thereby preventing other applications from playing sound), make sure the module snd_pcm_oss is not being loaded at boot. 
# https://wiki.archlinux.org/index.php/PulseAudio#ALSA
blacklist snd_pcm_oss
