---
- name: enable multilib repo
  ini_file:
    path: /etc/pacman.conf
    section: "multilib"
    option: "Include"
    value: "/etc/pacman.d/mirrorlist"
    state: present
  become: yes
  when: ansible_facts['architecture'] == 'x86_64'

- name: enable color
  ini_file:
    path: /etc/pacman.conf
    section: "options"
    option: "Color"
    allow_no_value: yes
    state: present
  become: yes

- name: enable parallel compilation
  ini_file:
    path: /etc/makepkg.conf
    section: null
    option: "MAKEFLAGS"
    value: "-j$(nproc)"
    no_extra_spaces: yes
    state: present
  become: yes
  when: pacman_parallel_compilation|default(False)

- name: enable parallel compression
  ini_file:
    path: /etc/makepkg.conf
    section: null
    option: "COMPRESSXZ"
    value: "(xz -c -z - --threads=0)"
    no_extra_spaces: yes
    state: present
  become: yes
  when: pacman_parallel_compression|default(False)

- name: run pacman update and upgrade
  pacman: update_cache=yes upgrade=yes
  become: yes

- name: install reflector
  pacman: name=reflector state=present
  become: yes
  tags: ['reflector']

- name: configure reflector
  lineinfile:
    path: /etc/xdg/reflector/reflector.conf
    regexp: "^{{ item.option }}.*"
    line: "{{ item.option }} {{ item.value }}"
    state: present
  loop:
    - { option: "--protocol", value: "https" }
    - { option: "--sort", value: "age" }
    - { option: "--latest", value: "5" }
    - { option: "--country", value: "{{ pacman_mirror_country }}" }
  become: yes
  tags: ['reflector']

- name: enable and reflector timer
  service:
    name: reflector.timer
    state: started
    enabled: yes
  become: yes
  tags: ['reflector']

- name: install pacman base packages
  pacman:
    name: "{{ pacman_base_packages }}"
    state: present
  become: yes

- name: install common utilities
  pacman:
    name: "{{ common_util_packages }}"
    state: present
  when: common_util_packages|default([])|length > 0
  become: yes

- include: aur.yml

- include: hooks.yml
  tags: ['hooks']
