---
- name: install khal
  pacman:
    name: khal
    state: present
  become: yes

- name: create khal config directory
  file:
    path: "{{ agenda_khal_config_path }}"
    state: directory
  become: yes
  become_user: "{{ user_name }}"

- name: template khal config
  template:
    src: khal-config.j2
    dest: "{{ agenda_khal_config_path }}/config"
  become: yes
  become_user: "{{ user_name }}"
