---
- name: check required
  assert:
    that:
      - "{{ item }}"
  with_items: "{{ agenda_required }}"
  tags: ['vdirsyncer', 'calendar', 'contacts']

- include: vdirsyncer.yml
  tags: ['vdirsyncer']

- include: calendar.yml
  tags: ['calendar']

- include: contacts.yml
  tags: ['contacts']

