---
- name: check required
  assert:
    that:
      - "{{ item }}"
  with_items: "{{ agenda_required }}"
  tags: ['vdirsyncer', 'calendar', 'contacts', 'thunderbird']

- include: vdirsyncer.yml
  tags: ['vdirsyncer']

- include: calendar.yml
  tags: ['calendar']

- include: contacts.yml
  tags: ['contacts']

- name: install thunderbird
  pacman:
    name: thunderbird
    state: present
  become: yes
  tags: ['thunderbird']
  when: agenda_install_thunderbird

