---
- name: check required
  assert:
    that:
      - "{{ item }}"
  with_items: "{{ agenda_required }}"

- include: vdirsyncer.yml
  tags: ['vdirsyncer']

- include: calendar.yml
  tags: ['calendar']

