---
power_handler_power_key: "{{ vault_power_handler_power_key }}"
# size in GB
power_swap_file_length: "{{ vault_power_swap_file_length }}"

user_name: "{{ vault_user_name }}"
user_password: "{{ vault_user_password }}"
user_dotfiles_url: "https://gitlab.com/ntfc/dotfiles.git"
user_dotfiles_path: "/home/{{ user_name }}/dotfiles"
user_ssh_key_passphrase: "{{ vault_user_ssh_key_passphrase }}"

bluetooth_install: "{{ vault_bluetooth_install }}"
# whether the bluetooth service should be started and enabled
bluetooth_enabled: "{{ vault_bluetooth_enabled }}"

gui_wm_default: "{{ vault_gui_wm_default }}"
gui_i3_config: "{{ vault_gui_i3_config }}"

audio_alsa_conf: "{{ vault_audio_alsa_conf }}"

git_email: "{{ vault_git_email }}"
git_gpg_sign_key: "{{ vault_git_gpg_sign_key }}"

openssh_client: "{{ vault_openssh_client }}"
openssh_hosts: "{{ vault_openssh_hosts }}"
openssh_server: "{{ vault_openssh_server }}"

agenda_vdirsyncer_enabled: "{{ vault_agenda_vdirsyncer_enabled }}"
agenda_khal_enabled: "{{ vault_agenda_khal_enabled }}"
agenda_vdirsyncer_calendars: "{{ vault_agenda_vdirsyncer_calendars }}"
agenda_khard_enabled: "{{ vault_agenda_khard_enabled }}"
agenda_vdirsyncer_contact_books: "{{ vault_agenda_vdirsyncer_contact_books }}"

cups_drivers_aur: "{{ vault_cups_drivers_aur }}"
