---
- block:
  - name: install gnome-keyring
    pacman:
      name:
        - gnome-keyring
        - libsecret # Access the GNOME keyring through `secret-tool`
        # - libgnome-keyring # deprecated, but required by some applications
        - python-keyring # can access the system keyring via `keyring`
        - seahorse # UI for Gnome Keyring
      state: present
    become: yes

  tags:
    - gnome-keyring
    - keyring
