---
agenda_vdirsyncer_config_path: ~/.config/vdirsyncer
agenda_vdirsyncer_path: ~/.local/share/vdirsyncer
agenda_vdirsyncer_status_path: "{{ agenda_vdirsyncer_path }}/status"

agenda_khal_config_path: ~/.config/khal

agenda_khard_config_path: ~/.config/khard

agenda_install_thunderbird: False
