---
- name: install vim
  pacman:
    name:
      - gvim
      #- vim
    state: present
  become: yes
  
  # this font is defined in URxvt XResources configuration
- name: install powerline font
  aur:
    use: "{{ aur_helper }}"
    name: ttf-dejavu-sans-mono-powerline-git
  become: yes
  become_user: "{{ aur_user }}"

- name: stow vim
  command: "stow -d ~/dotfiles -t ~/ vim"
  become: yes
  become_user: "{{ user_name }}"

- name: install Vundle
  git:
    accept_hostkey: yes
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: "~/.vim/bundle/Vundle.vim"
    version: "master"
  become: yes
  become_user: "{{ user_name }}"

- name: install node and yarn (required for coc.nvim)
  pacman: name=nodejs,yarn state=present
  become: yes

- name: run Vundle plugin update
  command: "/usr/bin/vim +PluginUpdate +qall!"
  become: yes
  become_user: "{{ user_name }}"

