- hosts: all
  pre_tasks:
    - name: check required
      assert:
        that:
          - aur_helper is defined
          - aur_user is defined
  roles:
    - role: user
      tags: ['user', 'usermod']
    - role: gui
      tags: ['gui']
    - role: screenlock
      tags: ['lock', 'screenlock']
    - role: cli
      tags: ['cli']
    - role: vim
      tags: ['vim']
    - role: git
      tags: ['git']
    - role: browser
      tags: ['web', 'browser']
    - role: agenda
      tags: ['agenda']
    - role: syncthing
      tags: ['syncthing']

