- hosts: all
  tags: ['multimedia', 'audio', 'video']
  pre_tasks:
    - name: check required
      assert:
        that:
          - aur_helper is defined
          - aur_user is defined
  tasks:
    - name: install common audio/video codecs/libs
      pacman:
        name:
          - flac
          - lame
          - libogg
          - libmatroska
          - x264
          - x265
          - wavpack

    - name: install gstreamer
      pacman:
        name:
          - gst-plugins-bad
          - gst-plugins-base
          - gst-plugins-good
          - gst-plugins-ugly
        state: present
      become: yes

    - name: install audio/video players
      pacman:
        name:
          - clementine
          - ffmpeg
          - obs-studio
          - vlc
        state: present
      become: yes

    ## current qt5 is not very stable, wait a bit..
    #- name: install puddletag
    #  aur:
    #    name: puddletag-qt5-git
    #    use: "{{ aur_helper }}"
    #  become: yes
    #  become_user: "{{ aur_user }}"

    - name: install v4l2loopback
      aur:
        use: "{{ aur_helper }}"
        name:
          - obs-v4l2sink
          - v4l2loopback-dkms
      become: yes
      become_user: "{{ aur_user }}"
      tags: ['v4l2']
