- hosts: all
  tags: ['office']
  tasks:
    - name: install cups
      pacman:
        name:
          - cups
          - system-config-printer
        state: present
      become: yes

    - name: install printing drivers (aur)
      aur:
        name: "{{ item }}"
        use: "{{ aur_helper }}"
      loop: "{{ cups_drivers_aur }}"
      become: yes
      become_user: "{{ aur_user }}"
      when: cups_drivers_aur|default([])|length > 0

    - name: install libreoffice
      pacman:
        name: libreoffice-still
        state: present
      become: yes

    - name: install evince
      aur:
        name: evince-light
        use: "{{ aur_helper }}"
      become: yes
      become_user: "{{ aur_user }}"

    - name: install zathura
      pacman:
        name:
          - zathura
          - zathura-ps
          - zathura-djvu
          - zathura-pdf-mupdf
        state: present
      become: yes

    - name: stow zathura
      command: "stow -d {{ user_dotfiles_path }} -t ~ zathura"
      become: yes
      become_user: "{{ user_name }}"

    - name: install calibre
      pacman: name=calibre state=present
      become: yes

    - name: install calculator
      pacman: name=speedcrunch state=present
      become: yes

    - name: install geany
      pacman:
        name:
          - geany
          - geany-plugins
        state: present
      become: yes

    - name: install jrnl
      pacman:
        name: jrnl
        state: present
      become: yes
