- hosts: all

  tasks:
    - name: install base python packages
      pacman:
        name: 
            # the virtualenvwrapper is enabled through dotfiles
          - python-virtualenvwrapper # https://wiki.archlinux.org/index.php/Python/Virtual_environment#virtualenvwrapper
        state: present
      become: yes
      tags: ['python']

    - name: install npm
      pacman:
        name:
          - npm
        state: present
      become: yes
      tags: ['npm']
