- hosts: all
  tags: ['java']
  tasks:
    - name: install java development tools
      pacman:
        name:
          - groovy
          - jdk-openjdk
          - maven # zsh completion provided by zsh-completions
          - jdk8-openjdk # mostly for compability reasons
          - openjdk-doc
          - openjdk-src
          - visualvm
        state: present
      become: yes

    - name: add java environment to /etc/profile
      ini_file:
        path: /etc/environment
        section: null
        option: "_JAVA_OPTIONS"
        value: "'-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true'"
        no_extra_spaces: true
        state: present
      become: yes

    - name: install intellij
      aur:
        name:
          - intellij-idea-ultimate-edition
          - intellij-idea-ultimate-edition-jre # provides better font rendering
        use: "{{ aur_helper }}"
      become: yes
      become_user: "{{ aur_user }}"

    # TODO: stow intellij settings
