---
- name: install syncthing
  pacman:
    name:
      - syncthing
      - syncthing-gtk
    state: present
  become: yes

- name: start and enable syncthing for user
  service:
    name: "syncthing@{{ user_name }}"
    enabled: yes
    state: started
  become: yes
