---
user_required:
  - user_name is defined
  - user_password is defined
  - user_password_salt is defined
  - user_group is defined
  - user_groups is defined and user_groups|length > 0
  - user_create_home is defined
  - user_is_sudoer is defined

# user's primary group
user_group: users
# user's secondary groups
user_groups:
  - wheel
  - network
user_create_home: yes
user_is_sudoer: yes
